name: macro_builder

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  analyzer: ^3.3.1
  build: ^2.2.1
  code_builder: ^4.1.0
  dart_style: ^2.2.2
  glob: ^2.0.2
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.1
