name: Generate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  bsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run ffigen --config lib/src/bsd/ffigen.yaml
    - run: ./.github/scripts/check-outdated-files.sh
      continue-on-error: true
    - uses: peter-evans/create-pull-request@v3
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate BSD bindings'
        commit-message: 'Regenerate BSD bindings'
        add-paths: lib/src/bsd/ffigen.dart
        branch: regenerate/bsd
        delete-branch: true

  gnu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - run: sudo apt install -y libclang-9-dev
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run ffigen --config lib/src/gnu/ffigen.yaml
    - run: ./.github/scripts/check-outdated-files.sh
      continue-on-error: true
    - uses: peter-evans/create-pull-request@v3
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate GNU bindings'
        commit-message: 'Regenerate GNU bindings'
        add-paths: lib/src/gnu/ffigen.dart
        branch: regenerate/gnu
        delete-branch: true

  macros:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run build_runner build --delete-conflicting-outputs
    - run: ./.github/scripts/check-outdated-files.sh
      continue-on-error: true
    - uses: peter-evans/create-pull-request@v3
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate macros'
        commit-message: 'Regenerate macros'
        add-paths: '**/*.g.dart'
        branch: regenerate/macros
        delete-branch: true
